// QUESTÕES PÚBLICAS — MOBILE — EE PROFESSOR JOÃO PRADO MARGARIDO
const QUESTOES_MOBILE = [
{id:"m1",texto:"Segundo o material de Mobile, o que torna um componente realmente reutilizável?",alternativas:["Ser criado novamente em cada tela.","Ser modular e parametrizável.","Ter sempre o mesmo texto e a mesma função.","Funcionar apenas na tela inicial."]},
{id:"m2",texto:"Como os temas claro e escuro beneficiam componentes reutilizáveis?",alternativas:["Obrigando a criar um componente novo para cada tema.","Permitindo que o mesmo componente adapte sua aparência ao tema escolhido.","Impedindo alterações de cores no aplicativo.","Fazendo o componente funcionar somente no modo escuro."]},
{id:"m3",texto:"Qual é uma vantagem de dividir um componente grande e complexo em partes menores?",alternativas:["Aumentar a duplicação de código.","Facilitar a localização de erros, alterações e testes.","Impedir que cada parte seja testada separadamente.","Deixar todos os componentes dependentes entre si."]},
{id:"m4",texto:"O que é usabilidade em um aplicativo ou site?",alternativas:["A facilidade que uma pessoa tem para utilizar o aplicativo ou site.","A quantidade de arquivos armazenados no aplicativo.","O número de cores usadas na interface.","A velocidade da conexão com o banco de dados."]},
{id:"m5",texto:"Qual é o primeiro passo apresentado no material para planejar testes de acessibilidade e usabilidade?",alternativas:["Realizar testes automatizados imediatamente.","Identificar o público-alvo.","Criar um banco de dados.","Publicar o aplicativo."]},
{id:"m6",texto:"Qual leitor de tela é indicado nos slides para iPhone e iPad com iOS?",alternativas:["VoiceOver","TalkBack","JAWS","Sentry"]},
{id:"m7",texto:"Qual métrica é apresentada como uma das melhores para avaliar a usabilidade de uma tarefa?",alternativas:["Quantidade de imagens da tela.","Tamanho do arquivo do aplicativo.","Tempo para completar uma tarefa.","Quantidade de cores utilizadas."]},
{id:"m8",texto:"Qual é uma característica principal de um banco de dados relacional destacada no material?",alternativas:["Não utilizar tabelas.","Possuir relações bem definidas entre tabelas.","Guardar apenas imagens.","Funcionar somente sem internet."]},
{id:"m9",texto:"No exemplo do Firebase, o que significa sincronização de dados em tempo real?",alternativas:["Os dispositivos podem receber atualizações praticamente no mesmo momento, sem atualização manual.","Os dados são atualizados somente uma vez por dia.","O usuário precisa reiniciar o celular para receber novos dados.","O aplicativo não pode trocar informações com outros dispositivos."]},
{id:"m10",texto:"O que são dados em trânsito?",alternativas:["Informações já guardadas permanentemente no banco de dados.","Arquivos que foram excluídos do aplicativo.","Informações que estão viajando de um dispositivo para outro.","Dados que existem apenas dentro do código-fonte."]},
{id:"m11",texto:"Qual tecnologia é apresentada para proteger dados enquanto eles passam pela internet?",alternativas:["CSS Grid","TLS/SSL","Logcat","Cache"]},
{id:"m12",texto:"Qual é a função do hashing de senha apresentada nos slides?",alternativas:["Enviar a senha para todos os usuários.","Deixar a senha visível no banco de dados.","Transformar a senha em outro valor para evitar armazenar diretamente a senha original.","Substituir o banco de dados por um arquivo de texto."]},
{id:"m13",texto:"Para que o Sentry pode ser utilizado em uma aplicação?",alternativas:["Acompanhar erros e registrar informações sobre onde e quando eles ocorreram.","Criar wireframes automaticamente.","Substituir o banco de dados relacional.","Criar temas claro e escuro."]},
{id:"m14",texto:"O que é o Logcat no contexto apresentado nos slides?",alternativas:["Um serviço de armazenamento em nuvem.","Uma ferramenta do Android que exibe mensagens sobre o que acontece no aplicativo.","Um programa usado apenas para criar protótipos.","Uma técnica de criptografia de senhas."]},
{id:"m15",texto:"No Logcat, o que representa o nível E?",alternativas:["Verbose","Debug","Error","Info"]},
{id:"m16",texto:"O que significa armazenamento em nuvem segundo o material?",alternativas:["Guardar arquivos e dados em servidores acessados pela internet.","Salvar tudo apenas na memória do celular.","Guardar arquivos exclusivamente em um pendrive.","Manter dados apenas enquanto o aplicativo está aberto."]},
{id:"m17",texto:"No AWS S3, o que é um bucket?",alternativas:["Uma ferramenta de criação de protótipos.","Um recipiente ou grande pasta na nuvem usado para organizar e armazenar arquivos.","Um leitor de tela do Android.","Um tipo de senha temporária."]},
{id:"m18",texto:"Qual é a função de uma URL assinada?",alternativas:["Deixar um arquivo público permanentemente.","Apagar automaticamente todos os arquivos de um bucket.","Dar acesso a determinado arquivo por um período limitado.","Substituir as permissões do sistema operacional."]},
{id:"m19",texto:"Qual é a principal diferença entre wireframe e protótipo apresentada nos slides?",alternativas:["Wireframe serve para banco de dados e protótipo para segurança.","Wireframe é usado somente em sites e protótipo somente em aplicativos.","Wireframe cria código pronto e protótipo cria tabelas.","Wireframe organiza a tela e protótipo permite simular a interação do usuário."]},
{id:"m20",texto:"Como o cache pode ajudar no desempenho de um aplicativo?",alternativas:["Apagando tudo que já foi carregado.","Guardando temporariamente algo que já foi carregado para evitar buscar a mesma informação várias vezes.","Forçando o aplicativo a carregar todos os dados novamente.","Impedindo o uso de Lazy Loading."]}
];
